### ISSUE TITLE
Compiling problems

### ISSUE THREAD

**Issue by anagno** [yufanmiao/imretOpenMVG#2]
Hi,

Using the instructions on the source code I am getting some unedified references to. For more informations look at the pull request https://github.com/yufanmiao/imretOpenMVG/pull/1

Kind regards

Vasilis

**Comment by yufanmiao** [comment]
Hi, Vasilis!

Glad to hear from you! And thank you for reporting the issue.

I think the problem you mentioned is one bug of the OpenMVG library, which is not a big problem. The remedy was introduced in the second step of my readme file in the docs folder.

For your convenience, you can run the following commands to create a new folder called sift in whereever the include files of the openMVG_dependencies are installed. Then move files outside it into the newly created sift folder. For me, and by default, those files are installed in /usr/local/include/openMVG_dependencies/nonFree

So the commands are:
sudo mkdir /usr/local/include/openMVG_dependencies/nonFree/sift
sudo cp -r vl sift
sudo cp SIFT_describer.hpp sift

Besides, just FYI,  you probably want to make sure that when you cmake flann, you need to enable the openMP for multi-thread computing. This is usually set by default and thus was not mentioned in the readme file. But just in case, it would be good to double check. And I updated the source code just now because I did not use the multi-thread function in FLANN correctly in the program I uploaded earlier.

Have fun with it! Please let me know when there are still troubles.

Kind regards
Yufan

**Comment by anagno** [comment]
Hi Yufan,

If you check the pull request https://github.com/yufanmiao/imretOpenMVG/pull/1 you will see that I had made a small change in the imretFuncs.hpp. You had forgotten to include the sub folder and that is why the compiler could not find the SIFT_describer.hpp. When I installed OpenMVG my folders were like:

```
vanagnos@vanagnos:/usr/local/include/openMVG_dependencies/nonFree$ ls -alR
.:
total 12
drwxr-xr-x 3 root root 4096 Nov  4 12:05 .
drwxr-xr-x 6 root root 4096 Nov  4 11:01 ..
drwxr-xr-x 3 root root 4096 Nov  4 11:01 sift

./sift:
total 20
drwxr-xr-x 3 root root 4096 Nov  4 11:01 .
drwxr-xr-x 3 root root 4096 Nov  4 12:05 ..
-rw-r--r-- 1 root root 6609 Nov  4 10:32 SIFT_describer.hpp
drwxr-xr-x 2 root root 4096 Nov  4 11:01 vl

./sift/vl:
total 108
drwxr-xr-x 2 root root  4096 Nov  4 11:01 .
drwxr-xr-x 3 root root  4096 Nov  4 11:01 ..
-rw-r--r-- 1 root root 10613 Nov  4 10:32 generic.h
-rw-r--r-- 1 root root 16495 Nov  4 10:32 host.h
-rw-r--r-- 1 root root  6075 Nov  4 10:32 imopv.h
-rw-r--r-- 1 root root  1768 Nov  4 10:32 imopv_sse2.h
-rw-r--r-- 1 root root 17128 Nov  4 10:32 mathop.h
-rw-r--r-- 1 root root  1487 Nov  4 10:32 mathop_sse2.h
-rw-r--r-- 1 root root 13516 Nov  4 10:32 mser.h
-rw-r--r-- 1 root root  3962 Nov  4 10:32 random.h
-rw-r--r-- 1 root root 11837 Nov  4 10:32 sift.h
```

So by changing the #include to "openMVG_dependencies/nonFree/sift/SIFT_describer.hpp" everything was resolved. Have you hard coded somewhere else the location of the library ?

As far as it concerns flann I have installed it from the package manager of ubuntu (https://launchpad.net/ubuntu/+source/flann). The library seems to be link against the GCC OpenMP support library (GOMP)

```
vanagnos@vanagnos:/lib$ ldd /usr/lib/x86_64-linux-gnu/libflann.so.1.8.4
    linux-vdso.so.1 =>  (0x00007fff6e514000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5290411000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f529010b000)
```

_libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f528fefc000)_

```
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f528fce6000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f528f921000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f5290e0c000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f528f703000)
```

Is there a specific reason that I will have to compile flann from source code ?

Also I think the problem resides somewhere with the OpenMVG library. What parameters did you used when you compiled the library ?

Thank you in advance

Vasilis

**Comment by yufanmiao** [comment]
Hi!

Thank you for pointing this out. As you pointed out, I did include the wrong path. It works on my laptop because in the path I included, there is also a SIFT_describer.hpp file. I guess it was because I wanted to compromise my code with the initially compiled results of openMVG. However, since the sift subfolder is required by openMVG samples if you want to run them, it is better to add it.

And the reason why we want to compile FLANN from source code is that openMVG is only supported with FLANN 1.80+. If the one you installed with the package manager is the correct version, then it should be working. I used all the default parameters when compiling FLANN. So it should be working.

Kind regards
Yufan

**Comment by anagno** [comment]
Hi,

My version of flann is 1.8.4 . I don`t have any problem compiling the libraries and everything works. My problem is linking them. When I try to compile your program I am getting linkings problems:

```
vanagnos@vanagnos:~/imretOpenMVG/build$ make
-- ----
-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 0.8.1
-- Installed in: /usr/local
-- Used OpenMVG libraries: openMVG_image;openMVG_features;openMVG_matching_image_collection;openMVG_kvld;openMVG_multiview;openMVG_lInftyComputerVision;openMVG_system;openMVG_sfm
-- ----
-- ----
-- OpenMVG Find_Package
-- ----
-- Found OpenMVG version: 0.8.1
-- Installed in: /usr/local
-- Used OpenMVG libraries: openMVG_image;openMVG_features;openMVG_matching_image_collection;openMVG_kvld;openMVG_multiview;openMVG_lInftyComputerVision;openMVG_system;openMVG_sfm
-- ----
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vanagnos/imretOpenMVG/build
[ 16%] Automatic moc and uic for target mainwindow
[ 16%] Built target mainwindow_automoc
[ 16%] Built target imretFuncs
[ 50%] Built target mainwindow
[ 66%] Automatic moc and uic for target main
[ 66%] Built target main_automoc
Linking CXX executable main
libmainwindow.a(mainwindow.cpp.o): In function `openMVG::features::SIFT_Image_describer::Describe(openMVG::image::Image<unsigned char> const&, std::unique_ptr<openMVG::features::Regions, std::default_delete<openMVG::features::Regions> >&, openMVG::image::Image<unsigned char> const*)':
mainwindow.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0xc9): undefined reference to `vl_constructor'
mainwindow.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0xfd): undefined reference to `vl_sift_new'
mainwindow.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x1d2): undefined reference to `vl_sift_process_first_octave'
mainwindow.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x27d): undefined reference to `vl_sift_detect'
mainwindow.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x2b7): undefined reference to `vl_sift_update_gradient'
mainwindow.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x3bf): undefined reference to `vl_sift_calc_keypoint_orientations'
mainwindow.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x439): undefined reference to `vl_sift_calc_keypoint_descriptor'
mainwindow.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x5aa): undefined reference to `vl_sift_process_next_octave'
mainwindow.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x5c3): undefined reference to `vl_sift_delete'
mainwindow.cpp:(.text._ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_[_ZN7openMVG8features20SIFT_Image_describer8DescribeERKNS_5image5ImageIhEERSt10unique_ptrINS0_7RegionsESt14default_deleteIS8_EEPS5_]+0x5cf): undefined reference to `vl_destructor'
collect2: error: ld returned 1 exit status
make[2]: *** [main] Error 1
make[1]: *** [CMakeFiles/main.dir/all] Error 2
make: *** [all] Error 2
```

I think the problem is in SiftGPU or in openMVG. Could you describe with details how you compiled the libraries (what parameters did you used during the compilation) and how you installed them in the operating system ? 
Could you also try and compile your program in a clean installation of ubuntu and document the steps you have to do to make it work?

Thanks in advance

Vasilis

**Comment by yufanmiao** [comment]
Hi!

Lets have a Skype chat :)

Kind regards
Yuan

**Comment by anagno** [comment]
Hi,

No need! I have just solve it! I had to link against vlsift. I added it in the pull request. If you can, document the dependencies through cmake and don`t count on the operating system and to the compiler to resolve the dependencies.

Kind regards 

Vasilis

**Comment by yufanmiao** [comment]
Hi,
Good to know that you have solved the problem. 

I can work on the dependencies.

Kind regards
Yufan
